version: 0.2

phases:
  install:
    on-failure: ABORtT
    runtime-versions:
      python: 3.9
    commands:
      - pwd
      - echo "Install Phase"
    finally:
      - echo "I am in finally block in the install stage"
      - sam --version
      - python --version
  build:
    on-failure: ABORT
    commands:
      - sam package --template-file template.yaml --output-template-file packaged-template.yml
    finally:
      - echo "Packaged"
artifacts:
  files:
    - packaged-template.yml

  #sam deploy --template-file /codebuild/output/src3166447627/src/packaged-template.yml --stack-name <YOUR STACK NAME>