AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  TollApp

  Sample SAM Template for TollApp

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  FunctionOne:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/FunctionOne
      Handler: app.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
  FunctionTwo:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/FunctionTwo
      Handler: app.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64

#  Function02:
#    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
#    Properties:
#      CodeUri: hello_world_function
#      Handler: hello_world/app.lambda_handler
#      Runtime: python3.10
#      Architectures:
#        - x86_64


Outputs:
  Function01Arn:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt FunctionOne.Arn